pipeline {
    agent any 
    stages {
        stage ("Clean WorkSpace") {
            steps {
            cleanWs()
            }
        }
        stage ("Code") {
            steps {
                git branch: 'images',
                url: 'https://github.com/avinashdevops0/Devops_Docker_Notes.git'
            }
        }
        stage ("Image and Running Container") {
            steps {
                dir("Static_HTML_Dashboard-app") {
                    sh "docker build --no-cache -t f:${BUILD_NUMBER} ."
                    // Remove container if already exists
                    sh "docker rm -f c1 || true"

                    // Run new container
                    // sh "docker run -d --name c1 -p 80:80 f:${BUILD_NUMBER}"
                    sh "docker run -d --name c1 -p 80:80 -m 256m --memory-swap 256m f:${BUILD_NUMBER}"
                }
            }
        }
    }
}