version: "3.8"

services:
  coffee_db:
    build: ./database
    image: "avinashg0/coffee_db"
    ports:
      - 3306
  
  coffee_be:
    build: ./backend
    image: "avinashg0/coffee_be"
    ports:
      - 3000
    env_file:
      - ./.env
  
  coffee_fe:
    build: ./frontend
    image: "avinashg0/coffee_fe"
    ports:
      - 80
  