FROM mysql:8.0.44-debian
COPY  /docker-entrypoint-initdb.d/
EXPOSE 3306
ENV MYSQL_ROOT_PASSWORD=rootpassword
# ENV MYSQL_DATABASE=task_manager
# ENV MYSQL_USER=dev_task_manager
# ENV MYSQL_PASSWORD=password123

